"""
Brandyn Gilbert
    Sat Mar 14 12:47:54 2020
    Project Euler
    Problem 2
"""
#PLAN
# =============================================================================
# # Even Fibonacci numbers
#
# # Problem 2
# # Each new term in the Fibonacci sequence is generated by adding the previous
# # two terms. By starting with 1 and 2, the first 10 terms will be:
#
# # 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# # By considering the terms in the Fibonacci sequence whose values do not
# # exceed four million, find the sum of the even-valued terms.
# =============================================================================


def main():
    i = 0
    a = 1
    b = 1
    total = 0

    no_lam(i, a, b, total)
    yes_lam(i, a, b, total)


def no_lam(i, a, b, total):
    while a < 4000000 and b < 4000000:
        i += 1
        if i%2 == 0:
            b = a + b
            if b % 2 == 0:
                total += b
        else:
            a = a + b
            if a % 2 == 0:
                total += a
    print('python:', total)

def yes_lam(i, a, b, total):
    fibo = lambda x, y: x + y
    while a < 4000000:
        i += 1
        c = fibo(a, b)
        b = a
        a = c
        if a%2 == 0:
            total += a


    print('lambda:', total)

if __name__ == "__main__":
    main()
